### ISSUE TITLE
Why not use the ring buffer like Disruptor

### ISSUE THREAD

**Issue by jackjoesh** [eBay/Gringofts#61]
Hi, why we don't use the ring buffer queues like Disruptor？  I found out that we are all using double buffered queues.
Is it because the double buffered queue totally avoids synchronization/mutex? Will it have better performance than ring buffer queue?
Thank you!

**Comment by jackyjia** [comment]
They both work, we chose Mpsc double buffered queue mainly for simplicity over performance. You will consider Disruptor-like ring buffer only if you work on low-latency trading app that single-digit micro matters.

**Comment by jackjoesh** [comment]
I would like to take a closer look. What is the main aspect of simplicity? Is it simple for you to implement this data structure, or is it simple and stable to use? We are also currently considering using Disruptor to solve some problems, and we are worried about whether it will be risky. thanks

**Comment by jackjoesh** [comment]
> They both work, we chose Mpsc double buffered queue mainly for simplicity over performance. You will consider Disruptor-like ring buffer only if you work on low-latency trading app that single-digit micro matters.

I would like to take a closer look. What is the main aspect of simplicity? Is it simple for you to implement this data structure, or is it simple and stable to use? We are also currently considering using Disruptor to solve some problems, and we are worried about whether it will be risky. thanks

**Comment by jackyjia** [comment]
let's say there are multiple stages on the pipeline, both MpscQueue and Disruptor takes care of passing data from the upstream to its successor. If the setup if one disruptor between each two stages, then it's roughly same with MpSc queue. If there's only one Disruptor for all stages, then you need to pay extra attention to the race condition, as it's more restricted, for example, data must be inserted at the first stage, stages in the middle cannot add new data to the Disruptor, more stages in the future will change the data structure.

**Comment by jackjoesh** [comment]
thank you ,  I understand
