### ISSUE TITLE
provide an interface to get raft members' offsets

### ISSUE THREAD

**Issue by crystal-xu** [eBay/Gringofts#62]
Providing such an interface could enable some advanced features. For example, reading from in-sync followers could be achieved by calculating the offset lags between followers and leader from the members' offsets returned by this interface. In that case slow followers with large lags could be evicted from the read list.

PR: https://github.com/eBay/Gringofts/pull/63

**Comment by jackyjia** [comment]
This is visible to the whole world, so please provide more context. @crystal-xu
