### ISSUE TITLE
Why in-memory state update is earlier than raft committed

### ISSUE THREAD

**Issue by jackjoesh** [eBay/Gringofts#64]
If raft committed has not been successful and server crash, resulting in changing leader,  it will cause the previously updated memory state to be discarded.
If an external service comes to query state before this, the abandoned state will be queried. Is this scenario tolerable?
Thank you

**Comment by jackyjia** [comment]
To financial services, the data returned must be committed.

EAL has the committed state, query service should access the state from EAL. The in-memory state is only in CPL as processing request needs the latest state, even it's not committed yet.

**Comment by jackjoesh** [comment]
got it, thank you
