### ISSUE TITLE
Support non-voting member role for Raft cluster

### ISSUE THREAD

**Issue by DongbinCheng** [eBay/Gringofts#84]
In order to avoid availability gaps, Raft introduces an additional phase before the configuration change, in which a new server joins the cluster as a non-voting member. The leader replicates log entries to it, but it is not yet counted towards majorities for voting or commitment purposes. 
The mechanism of non-voting servers can also be useful in other contexts. For example, it can be used to replicate the state to a large number of servers, which can serve read-only requests with relaxed consistency.

**Comment by crystal-xu** [comment]
[ISSUE-84: support non-voting member role for Raft cluster #85](https://github.com/eBay/Gringofts/pull/85)
